// Auto-generated by scripts/generate_demo_patients.py — do not edit by hand.
export interface DemoPatient {
  id: string;
  name: string;
  age: string;
  sex: string;
  story: string;
  conditions: string[];
}

export const DEMO_PATIENTS: DemoPatient[] = [
  {
    id: "d0be5a00-57c5-4417-adeb-824beb93e4c3",
    name: "John Doe",
    age: "62",
    sex: "male",
    story: "HTN diagnosed 2019 \u2192 CKD progression by 2022. Silent multi-year cardiometabolic cascade.",
    conditions: ["hypertension", "type 2 diabetes", "chronic kidney disease"],
  },
  {
    id: "a8c2f1d5-3e6b-4a91-9c4f-2d8e7b0a5f3c",
    name: "Maria Rodriguez",
    age: "58",
    sex: "female",
    story: "T2DM since 2020, struggled with control until SGLT2 added in 2023. UACR rising \u2014 early nephropathy.",
    conditions: ["type 2 diabetes", "hypertension", "early diabetic nephropathy", "dyslipidemia"],
  },
  {
    id: "b3e7d2a8-9f4c-4b1e-8a6d-c5f2b9e0a4d7",
    name: "Robert Chen",
    age: "71",
    sex: "male",
    story: "CHF (EF 35%) + AFib + COPD. Cardiorenal syndrome emerging \u2014 BNP rising, eGFR falling on optimized therapy.",
    conditions: ["heart failure", "atrial fibrillation", "COPD", "cardiorenal syndrome"],
  },
  {
    id: "f4a9c1e6-7b3d-4f82-8e5a-1d6c3f0b9a7e",
    name: "Sarah Williams",
    age: "45",
    sex: "female",
    story: "Prediabetes + borderline HTN caught at 2024 physical. Excellent response to lifestyle intervention \u2014 control case.",
    conditions: ["prediabetes", "borderline hypertension"],
  },
];
